development:
    adapter: postgresql
    encoding: unicode
    database: site_devel
    username: postgres
    password: postgres
    host: localhost

# Banco de teste. Nao confie em salvar nada aqui
test:
    adapter: postgresql
    encoding: unicode
    database: site_test
    username: postgres
    password: postgres
    host: 127.0.0.1

production:
    adapter: postgresql
    encoding: unicode
    database: site_prod
    username: postgres
    password: postgres
    host: localhost
